version: "3"
services:
  api:
    build: ./api
    volumes:
      - ./:/backend
      - /api/node_modules
    environment:
      - MYSQL_ROOT_HOST=${DB_ROOT_HOST}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports: 
      - "3000:8080"
    depends_on: # 依存関係(apiコンテナよりdbコンテナが先に起動する)
      - "db"
    networks:
      - backend
  db:
    image: mysql:5.7
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    tmpfs:
      - /var/lib/mysql
    networks:
      - backend
networks:
  backend:
